### PR TITLE
Skip unknowns in Check to avoid panic when marshalling Build object

### LINKED ISSUE #565: Image Build Args containing an resource output panics: "interface conversion: interface {} is resource.Computed, not resource.PropertyMap"
### What happened?

A panic occurs when building a docker image,  where the `Build.Args` InputMap contains an entry with an output from another resource.

```
Diagnostics:
  pulumi:pulumi:Stack (docker-test-dev):
    panic: interface conversion: interface {} is resource.Computed, not resource.PropertyMap
    goroutine 97 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/go/common/resource/properties.go:431
    github.com/pulumi/pulumi-docker/provider/v4.marshalArgs({{0x13eef40?, 0xc000389890?}})
        /home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:440 +0x217
    github.com/pulumi/pulumi-docker/provider/v4.marshalBuildAndApplyDefaults({{0x14fd6c0?, 0xc000470930?}})
        /home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:382 +0x245
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Check(0xc0007aec80, {0x17e35c8, 0xc0004708d0}, 0xc000115bc0)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:117 +0x205
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Check({{}, {0x21a1260, 0x25dfe, 0x25dfe}, {0x17cebd4, 0x6}, {0x17efb10, 0xc0005aa280}, {0x17efa60, 0xc0007aec80}}, ...)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:96 +0xd7
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x17e35c8, 0xc0004708d0}, {0x14bc260?, 0xc000115bc0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:537 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x17e35c8, 0xc000470690}, {0x14bc260, 0xc000115bc0}, 0xc0003179a0, 0xc0004902d0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x1532920?, 0xc0000b0fa0}, {0x17e35c8, 0xc000470690}, 0xc0006433b0, 0xc000477e40)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:539 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000308000, {0x17eb7c0, 0xc0005d2ea0}, 0xc00012ec60, 0xc0005786c0, 0x21e2ab0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
    google.golang.org/grpc.(*Server).handleStream(0xc000308000, {0x17eb7c0, 0xc0005d2ea0}, 0xc00012ec60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

  docker:index:Image (test):
    error: error reading from server: EOF
```

### Expected Behavior

The image to be created. This scenario worked as expected when using `Pulumi.Docker` 3.6.1.

### Steps to reproduce

```
public class DockerStack : Stack {

   public DockerStack() {
      // I just use a plugin here arbitrarily.  I think consuming output from any resource might cause the error
      var plugin = new Plugin("sample-plugin", new() {
         Envs = new[] {  "DEBUG=1"  },
      });

      var _ = new Image("test", new ImageArgs {
         SkipPush = true,
         ImageName = "hi",
         Build = new DockerBuildArgs {
            BuilderVersion = BuilderVersion.BuilderBuildKit,
            Context = "./",
            Dockerfile = "Dockerfile",
            Args = {
               // Using a resource output here as the arg value triggers a panic.  
               // Using a string literal or an output created from a Task<string> does not trigger.
               {"ARG_FROM_RESOURCE_OUTPUT", plugin.Id},
            },
         }
      });
   }
}

```

### Output of `pulumi about`

```
CLI          
Version      3.59.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.1.0
dotnet  unknown

Host     
OS       debian
Version  11.6
Arch     x86_64

This project is written in dotnet: executable='/usr/bin/dotnet' version='7.0.201'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jlewicki-nevo
User           jlewicki-nevo
Organizations  jlewicki-nevo

Dependencies:
NAME           VERSION
Pulumi         3.54.1
Pulumi.Docker  4.1.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
When we try to access a Build object which contains unknown values in the Check() function, the provider panics, because the Build object is not of the correct resource type.
This pull request ignores unknowns when reading inputs in Check(), allowing for the resulting object to be processed correctly.
Fixes #565.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
Is there a test we could add for this case?

**Review by iwahbe — COMMENTED** [review]
What will line 121 do if `build` is an unknown?

On line 179 we check if `input["build"]` is null? Will that work (not panic)? Will that do the wrong thing because `inputs` is actually unknown, not null.

**Comment by t0yv0** [comment]
It's good to fix the bug in any way we can for now! (if we can add a test).  Thinking forward, is there a chance that this is actually a platform issue? As I've attempted in https://github.com/pulumi/pulumi-docker/pull/435 it feels like there should be a way to code against a higher-level interface that hydrates a Go struct with appropriate err msgs, and concerns such as `input["build"]` panicking that Ian brings up would just not arise in that repr.

**Comment by guineveresaenger** [comment]
All good questions!

@mikhailshilkov I am completely open to suggestion here, but as this is SDK behavior, testing it here feels redundant at best and incorrect at worst.

@iwahbe - if we set `KeepUnknowns` to false, Check will throw away any unknowns. This means that Build will _never_ be an unknown. I looked at a few other Native providers (azure and k8s), and any `IsUnknown()` checks are quite rare throughout. As for line 121, it may be worth it to add an `IsNull()` check.

@ t0yv0 - I chatted with @Frassle about it this morning, and in the panic situation, the Build object becomes flattened during Check(), meaning if any one sub-field is Unknown, the entire object is Unknown. This does mean we lose access to any fields that _were_ set! However, for this use case, we don't actually need access to those fields since we're setting defaults.

**Comment by mikhailshilkov** [comment]
#565 has a repro so a baseline test could be exercising that repro in one of our end-to-end tests. I don't know if there is a lower-level test that would still make sense. Unit test `Check` and pass some unknowns?

**Comment by guineveresaenger** [comment]
@mikhailshilkov - ah, an integration test makes a lot more sense to me. Added!

**Comment by iwahbe** [comment]
> @iwahbe - if we set `KeepUnknowns` to false, Check will throw away any unknowns. This means that Build will _never_ be an unknown. I looked at a few other Native providers (azure and k8s), and any `IsUnknown()` checks are quite rare throughout. As for line 121, it may be worth it to add an `IsNull()` check.

I meant "What will this do if build is genuinely unknown. I understand the provider won't get a `resource.PropertyValue` (since we discard unknowns). I meant will we handle a `nil` value correctly everywhere. I believe that is what a discard unknown turns into.

**Comment by guineveresaenger** [comment]
@iwahbe - gotcha! This doesn't show up because it's in a different file, but `IsNull` is the first thing the Build marshaller checks: https://github.com/pulumi/pulumi-docker/blob/master/provider/image.go#L361 so I think we should be good here!

**Pull request merged**
