### PR TITLE
Upgrade terraform-provider-docker to v3.0.1

### LINKED ISSUE #419: Upgrade terraform-provider-docker to v2.23.1
Release details: https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v2.23.1

### LINKED ISSUE #447: Upgrade terraform-provider-docker to v2.24.0
Release details: https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v2.24.0

### LINKED ISSUE #452: Upgrade terraform-provider-docker to v2.25.0
Release details: https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v2.25.0

### LINKED ISSUE #456: Provider configuration Error
### What happened?

After upgrading to 3.6.1 I get the following error. There have been no code changes apart from the version upgrade

    error: could not validate provider configuration: 1 error occurred:
        * Attribute must be a single value, not a map

Rolling back to 3.6.0 fixes the error

### Steps to reproduce

Create a provider and add it to a resource ie an Image

### Expected Behavior

to be able to create a provider and attach it to a resaourceresource

### Actual Behavior

    error: could not validate provider configuration: 1 error occurred:
        * Attribute must be a single value, not a map

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #457: Upgrade terraform-provider-docker to v3.0.0
Release details: https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v3.0.0

### LINKED ISSUE #458: Upgrade terraform-provider-docker to v3.0.1
Release details: https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v3.0.1

### PR DESCRIPTION
**Pull request by aq17**
Fixes #458 
Fixes #457 
Fixes #456 
Fixes #452 
Fixes #447 
Fixes #419

### CODE REVIEW

**Comment by AaronFriel** [comment]
@guineveresaenger any objection to us releasing this while we keep working on v4?

**Comment by AaronFriel** [comment]
Actually, interesting question, this is a major version bump. That make "v4" into "v5".

**Comment by guineveresaenger** [comment]
I think it makes sense to merge this, but hold off on releasing our major version. Especially since there's not really any breaking schema changes.

**Review by guineveresaenger — APPROVED** [review]
Please merge but do not cut a release yet!

**Pull request merged**
