### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by rienafairefr**
@lukehoban I tried some things with the async code for docker Images, using asyncio-subprocess. 
do not merge as is, I modified the aws-py example, trying to get a reliable failure, building a few images sequentially seemed to do it.
With the new async code, the docker build does not seem to fail anymore. But there is still some problems (apparent deadlock) with the "docker login" (which passes stuff to the subprocess via stdin) case

### CODE REVIEW

**Comment by lukehoban** [comment]
@rienafairefr Just checking in whether you wanted to try to finish up these changes?  If not, I'll see about taking a look at them later this week.

**Comment by rienafairefr** [comment]
@lukehoban I'm still looking at it, I'd like some review and testing, using asyncio-subprocess is kinda working. it's been a shitshow to fix, sometimes it deadlocks, sometimes it exhausts the compute resources during build (if too many docker commands running at the same time I guess), sometimes the docker push (in the case of the aws-py example) looks kinda stuck, finally finishing after 10 minutes to push 10 times 50 MB, which is low.

If you want to try your hands, tell me what you find :-)

**Comment by komalali** [comment]
@rienafairefr thanks for the work you've done on this. I'm gonna try poking around and see if we can get this in.

**Comment by komalali** [comment]
@rienafairefr I'm going to close out this PR now as I continued what you started over at #169 and it is now merged in. Thanks again for your work here!

**Pull request closed without merging**
