### PR TITLE
upgrade to tfbridge v3.42.1

### PR DESCRIPTION
**Pull request by jazzyfresh**
official version for fixed docs generation

also
* [x] ~~added codegen~~
  * fixed this, there should be no codegen, i was using an old version of pulumi
* [x] fixed lint `ignoreMatcher.Matches` error for https://github.com/pulumi/pulumi-docker/issues/526#issuecomment-1460916355

### CODE REVIEW

**Comment by jazzyfresh** [comment]
I'm not sure why [build_sdk (python)](https://github.com/pulumi/pulumi-docker/actions/runs/4368963871/jobs/7642276685) step is failing, when i build locally there are no changes

**Comment by jazzyfresh** [comment]
closing as something is weird with my codegen here

**Comment by jazzyfresh** [comment]
issue was an outdated dev version of pulumi, re-ran make tfgen worked this time

**Review by AaronFriel — APPROVED** [review]
LGTM

**Pull request merged**
