### PR TITLE
Fix repeated docker image tags

### PR DESCRIPTION
**Pull request by mazamats**
Addresses: https://github.com/pulumi/pulumi-docker/issues/41

Open to any suggestions, feel free to make edits.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Definitely a bit nervous.  Can you make sure the 'containers' test passes on travis.  You can do that by editing this file and moving the following block: https://github.com/pulumi/pulumi-cloud/blob/d290510cfe029778820e336fb745291b99ae81f4/aws/aws_test.go#L145-L161

Into the 'shorttests' array above.  This will help us get coverage for a bunch of complex container cases we want to make sure we don't regress.  Thanks!

**Comment by mazamats** [comment]
@CyrusNajmabadi https://github.com/pulumi/pulumi-cloud/pull/655

Test doesn't actually run though since its a PR.

```console
    --- SKIP: Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/examples/containers (0.00s)
        program.go:412: Skipping: PULUMI_ACCESS_TOKEN is not set
```

**Comment by lukehoban** [comment]
Yeah - @CyrusNajmabadi we'll need to kick off a test run from a branch in our org to allow Travis to run tests to get some validation if needed.   @mazamats you could technically try running the test locally yourself instead of in Travis - and if you run just the `containers` test it should be fairly easy to do.

**Comment by CyrusNajmabadi** [comment]
I'll handle kicking off the tests.

**Comment by CyrusNajmabadi** [comment]
Continuing this pr with: https://github.com/pulumi/pulumi-docker/pull/42

**Pull request merged**
