### PR TITLE
Switch docker daemon connection test to use cli.Ping instead of cli.PluginList. Resolves #737

### LINKED ISSUE #737: docker.Image: Unusable in docker environments which restrict access to `docker plugin ls`
### What happened?

While attempting to build a docker image within a [Bitbucket](https://bitbucket.org/product) CI/CD pipeline, the following error is received.

> docker:index:Image my-container  error: Docker native provider returned an unexpected error from Configure: Error response from daemon: authorization denied by plugin pipelines:

Related debug events:
> event {"diagnosticEvent":{"color":"never","message":"RegisterResource RPC prepared: t=docker:index/image:Image, name=ukilrn-lab-containers-dev/ssh-server\n","prefix":"debug: ","severity":"debug"},"sequence":159,"timestamp":1694057702}
> event {"diagnosticEvent":{"color":"never","message":"2023/09/07 03:35:02 checking connection to docker daemon at tcp://localhost:2375\n","prefix":"debug: ","severity":"debug"},"sequence":161,"timestamp":1694057702}

### Expected Behavior

A successful docker image build.

### Steps to reproduce

Run the example docker image build within a Bitbucket pipeline (or any docker environment which prohibits `docker plugin ls`).

```
import * as pulumi from "@pulumi/pulumi";
import * as docker from "@pulumi/docker";

const demoImage = new docker.Image("demo-image", {
    build: {
        context: ".",
        dockerfile: "Dockerfile",
    },
    imageName: "username/image:tag1",
    skipPush: true,
});
export const imageName = demoImage.imageName;
```

### Output of `pulumi about`

CLI          
Version      3.80.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.5
Arch     arm64

### Additional context

This error is generated when pulumi-docker checks if the docker connection works by calling `cli.PluginList` but is blocked by Bitbucket's custom docker authorization plugin called "pipelines".

> Note: `docker plugin ls` is not listed within their [Restricted Commands](https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/#Running-Docker-commands) so I will submit an issue to them as well.

`docker info` from a Bitbucket pipeline:
```
Plugins:
  Authorization: pipelines
```

[provider/image.go](https://github.com/pulumi/pulumi-docker/blob/0c6b7105af9448c8c54b6b44e0177e613b76bc13/provider/image.go#L777):
```
// Check if the connection works. If not and we used the default host, try the user host.
// See "Adminless install on macOS" on https://www.docker.com/blog/docker-desktop-4-18/
log.Printf("checking connection to docker daemon at %s", host)
_, err = cli.PluginList(context.Background(), filters.Args{})
if err != nil && !isExplicitHost && runtime.GOOS != "windows" {
	home, err2 := os.UserHomeDir()
	if err2 != nil {
		return nil, err2
	}
	userSock := fmt.Sprintf("unix://%s/.docker/run/docker.sock", home)
	log.Printf("no connection to docker daemon at %s, trying %s (%v)", host, userSock, err)
	cli, err = configureDockerClientInner(configs, userSock)
	if err != nil {
		log.Printf("no connection to docker daemon at %s, stopping (%v)", host, err)
	}
}
```

One solution may be to use `cli.Info` rather than `cli.PluginList`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by korosccj**
Switch docker daemon connection test to use cli.Ping instead of cli.PluginList. Resolves #737

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Thank you so much for your contribution!

Let's hope a Ping works in this case. Running the tests for you 🤞 

/run-acceptance-tests

**Review by guineveresaenger — APPROVED** [review]

**Comment by guineveresaenger** [comment]
Tests pass; this looks like it's strictly an improvement; thank you very much!

**Comment by korosccj** [comment]
you're welcome, and thank you for maintaining this sweet project! 

Do you happen to know when the next release will go out to pickup this change? Just eager to update our pipelines 😄

**Comment by guineveresaenger** [comment]
I'll release a patch today 👍

**Comment by korosccj** [comment]
> I'll release a patch today 👍

Works perfectly! Ty!

**Pull request merged**
