### PR TITLE
Example of using auto mapper

### PR DESCRIPTION
**Pull request by t0yv0**
This would require a fix not yet in pulumi/pulumi: https://github.com/pulumi/pulumi/pull/11537

Yet it may be promising - the code for converting between the typed model (Image, Build) and resource.PropertyValue can be automated via the mapper package - the boilerplate can be removed or reduced.

### CODE REVIEW

**Comment by guineveresaenger** [comment]
This may be a reason to drop existing unions from the provider, although it would lock us into never having any:

https://github.com/pulumi/pulumi-docker/issues/428
https://github.com/pulumi/pulumi-docker/issues/427

**Comment by t0yv0** [comment]
I think unions are still a feature out there in the wild world of schemas. I'd keep this around w/o merging for a bit as something that informs the design of mapper module. Perhaps there's a trick we could teach mapper to do that would make working with unions more reasonable.

**Comment by AaronFriel** [comment]
@t0yv0 @guineveresaenger I think we can close this draft?

**Comment by t0yv0** [comment]
Up to @guineveresaenger  - I've not been up-to-date with latest docker changes, but strategically this still makes a lot of sense to me to finish up to make more custom resource development sustainable, so it should go on the backlog somewhere? That is:

- upstream improved serde facilities (PropertyValue <-> typed structs) into pulumi/pulumi/sdk
- use automatic serde instead of manual serializers

Automatic code is less error prone, easier to read and can be made to more predictably handle missing values with localized error messages. Manually written code typically misses an error case here or there.

I'm wondering though if there's something in the new-style provider SDK that can be used for this purpose instead of the automapper module from sdk/v3.

**Comment by t0yv0** [comment]
Ah I see the request is tracked in https://github.com/pulumi/pulumi/issues/11530 so that's good. Possibly need to put it on x-team request list. Without MarshalJSON/UnmarshalJSON style hooks in the automapper this is not practical.

**Pull request closed without merging**
